zabbix_export:
  version: '6.0'
  date: '2024-03-14T09:08:38Z'
  groups:
    - uuid: 36bff6c29af64692839d077febfc7079
      name: 'Templates/Network devices'
  templates:
    - uuid: 0f99c897a2fd47228eaf6be4117c41da
      template: 'Cisco IOS Config Check'
      name: 'Cisco IOS Config Check'
      description: |
        Requires user and pass macro:
        {$SSH_USER}
        {$SSH_PASS}
        
        ## Author
        Copyright (C) 2023 lestoilfante (https://github.com/lestoilfante)
        
        ## License
        GNU General Public License version 3 (GPLv3)
      groups:
        - name: 'Templates/Network devices'
      items:
        - uuid: bef51d3498144d85b19630cd4f8584b0
          name: 'Running Config'
          type: SSH
          key: 'ssh.run[showRunFull,{$SSH_IP}]'
          delay: '{$SSH_CFG.INTVAL}'
          history: '{$SSH_CFG.HISTORY}'
          trends: '0'
          value_type: TEXT
          params: 'show running-config view full'
          username: '{$SSH_USER}'
          password: '{$SSH_PASS}'
          description: |
            Runs a "show running-config view full" and keeps config history
            
            Set a readonly user on IOS device with low privilege level e.g.:
            	username readonly_user privilege 5
            	file privilege 5
            	privilege exec level 5 show running-config view full
          preprocessing:
            - type: STR_REPLACE
              parameters:
                - \r\n
                - \n
            - type: REGEX
              parameters:
                - '.*(![[:space:]]version \d[\s\S[:space:]]*)'
                - \1
            - type: DISCARD_UNCHANGED_HEARTBEAT
              parameters:
                - '{$SSH_CFG.HEARTBIT}'
          triggers:
            - uuid: 7c654fbdb544480cb9a70d075e40398d
              expression: 'nodata(/Cisco IOS Config Check/ssh.run[showRunFull,{$SSH_IP}],{$SSH_CFG.WARN})=1'
              name: 'Running config not retrieved'
              priority: WARNING
              description: 'No data has been retrieved lately, can be a connectivity issue'
            - uuid: e928a955f6634c7f910b554c13108b3c
              expression: 'last(/Cisco IOS Config Check/ssh.run[showRunFull,{$SSH_IP}],#1)<>last(/Cisco IOS Config Check/ssh.run[showRunFull,{$SSH_IP}],#2) and length(last(/Cisco IOS Config Check/ssh.run[showRunFull,{$SSH_IP}]))>0'
              recovery_mode: NONE
              name: 'Running config has changed'
              opdata: 'Running config has changed'
              priority: INFO
              description: |
                Running config has changed since last check.
                Must be closed manually
              manual_close: 'YES'
      macros:
        - macro: '{$SSH_CFG.HEARTBIT}'
          value: 2d
          description: 'Keep lower then {$SSH_CFG.WARN}'
        - macro: '{$SSH_CFG.HISTORY}'
          value: 60d
          description: 'History to keep'
        - macro: '{$SSH_CFG.INTVAL}'
          value: 24h
          description: 'Config retrieval frequency'
        - macro: '{$SSH_CFG.WARN}'
          value: 3d
          description: 'nodata() trigger'
        - macro: '{$SSH_IP}'
          description: 'Ssh IP'
        - macro: '{$SSH_PASS}'
          description: 'Ssh password'
        - macro: '{$SSH_USER}'
          description: 'Ssh user'
